CREATE TABLE test.SCHET(
	CODE_MO varchar(6) UNIQUE NOT NULL,
	YEAR numeric(4) NOT NULL CHECK (YEAR BETWEEN 1901 AND 9999),
	MONTH numeric(2) NOT NULL CHECK (MONTH BETWEEN 1 AND 12),
	NSCHET varchar(20),
	DSCHET date,
	PLAT varchar(5),
	COMMENTS varchar(250)
);

create table test.SLUCH(
	ID_SLUCH varchar(36) UNIQUE NOT NULL,
	ID_SCHET varchar(6) NOT NULL REFERENCES test.SCHET(CODE_MO) ON DELETE CASCADE ON UPDATE CASCADE,
	PR_NOV numeric(1) NOT NULL,
	VIDPOM numeric(2) NOT NULL,
	MODDATE date,
	BEGDATE date NOT NULL,
	ENDDATE date NOT NULL,
	MO_CUSTOM varchar(6) NOT NULL,
	LPUBASE numeric(7) NOT NULL,
	ID_STAT numeric(1) NOT NULL,
	SMO varchar(5),
	SMO_OK varchar(5),
	LPUCODE numeric(7) NOT NULL,
	NRP_MO varchar(6),
	NRP_TYPE numeric(1),
	NRP_MDCODE varchar(8),
	EXTR numeric(2) NOT NULL,
	NHISTORY varchar(50) NOT NULL,
	RSLT numeric(3) NOT NULL,
	ISHOD numeric(3) NOT NULL, 
	PRVS numeric(9) NOT NULL,
	PROFIL varchar(11) NOT NULL,
	DET numeric(1) NOT NULL,
	IDDOKT varchar(8) NOT NULL,
	SIGNPAY numeric(1) NOT NULL,
	IDSP numeric(2) NOT NULL,
	GRP_SK numeric(1),
	OPLATA numeric(1),
	ED_COL numeric check (ED_COL BETWEEN 5 AND 2),
	KOEFFCUR numeric check (KOEFFCUR BETWEEN 5 AND 2),
	IDSL numeric(4),
	KOL_MAT numeric check (KOL_MAT BETWEEN 5 AND 2),
	INV numeric(1),
	VNOV numeric(4),
	P_PER numeric(1),
	PODR numeric(8) NOT NULL,
	TAL_D date,
	TAL_P date,
	NPR_DATE date,
	SCH_CODE varchar(10),
	IT_TYPE varchar(10),
	SRM_MARK varchar(10),
	MSE numeric(1),
	USL_OK numeric(2) NOT NULL,
	COMENTSL varchar(250)
);

CREATE TABLE test.USL(
	ID_USL varchar(36) UNIQUE NOT NULL,
	SLUCH_ID varchar(36) NOT NULL REFERENCES test.SLUCH(ID_SLUCH) ON DELETE CASCADE ON UPDATE CASCADE,
	CODE_USL varchar(16) NOT NULL,
	PRVS numeric(9) NOT NULL,
	DATEUSL date NOT NULL,
	CODE_MD varchar(8) NOT NULL,
	SKIND numeric(2) NOT NULL,
	TYPEOPER numeric(3),
	INTOX varchar(15),
	DS_DENT varchar(10),
	PODR numeric(8) NOT NULL,
	PROFIL varchar(11) NOT NULL,
	DET numeric(1) NOT NULL,
	BEDPROF numeric(3),
	KOL_USL numeric NOT NULL CHECK (KOL_USL BETWEEN 2 AND 6),
	VID_VME varchar(15),
	NPL numeric(1),
	COMENTU varchar(250)
);